version: '3.1'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app/
    ports:
     - "3000:3000"
    environment:
      DB_PORT: 5432
      DB_HOST: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_DATABASE: postgres
    depends_on:
     - postgres
  postgres:
    image: postgres:11.2-alpine
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    build:
      context: .
      dockerfile: ./db/Dockerfile
